#!/bin/bash
set -ue

# docker run -v $PWD/test.csv:/opt/workdir/file.csv local/updategoogle

if [ $# -ne 1 ]; then 
    
    (>&2 echo "where's the file")
    exit 1

fi

if [[ "$(docker images -q kingsukhoi/updatedomains 2> /dev/null)" == "" ]]; then
    docker pull kingsukhoi/updatedomains
fi

docker run --rm -v $(realpath $1):/opt/workdir/file.csv kingsukhoi/updatedomains 
