#!/bin/bash
set -ue

# docker run -v $PWD/test.csv:/opt/workdir/file.csv local/updategoogle

if [ $# -ne 1 ]; then 
    
    (>&2 echo "where's the file")
    exit 1

fi

docker pull kingsukhoi/updatedomains

docker run --rm -v $(realpath $1):/opt/workdir/file.csv kingsukhoi/updatedomains 
